import { chromium, firefox, webkit, type Page } from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
const origin=process.env.CLOUD_ORIGIN!;
const engine=process.env.DASHBOARD_BROWSER||'chromium';
if(engine!=='chromium'&&engine!=='firefox'&&engine!=='webkit')throw new Error('Invalid DASHBOARD_BROWSER');
const output=process.env.QA_OUTPUT||fs.mkdtempSync('/tmp/layercache-cloud-browser-');fs.mkdirSync(output,{recursive:true});
const browser=await {chromium,firefox,webkit}[engine].launch({headless:true,...(engine==='chromium'?{executablePath:process.env.CHROMIUM_PATH||undefined,args:['--no-sandbox']}:{})});
const aliceContext=await browser.newContext({viewport:{width:1440,height:1050}}),bobContext=await browser.newContext({viewport:{width:390,height:844}});
const alice=await aliceContext.newPage(),bob=await bobContext.newPage();
const errors:string[]=[];for(const page of [alice,bob])page.on('pageerror',error=>errors.push(error.message));
const results:{name:string;passed:boolean;error?:string}[]=[];
async function check(name:string,fn:()=>Promise<void>){try{await fn();results.push({name,passed:true});}catch(error){results.push({name,passed:false,error:error instanceof Error?error.message:String(error)});await alice.screenshot({path:path.join(output,name.replace(/\W/g,'-')+'.png'),fullPage:true});throw error;}}
async function login(page:Page,user:string){await page.goto(origin);await page.getByRole('link',{name:'Continue with GitHub'}).click();await page.getByRole('link',{name:'Sign in as '+user}).click();await page.getByText('@'+user,{exact:true}).first().waitFor();}
function form(page:Page,title:string){return page.locator('form').filter({has:page.getByRole('heading',{name:title,exact:true})});}
try{
 await check('OAuth PKCE login two independent identities',async()=>{await login(alice,'alice');await login(bob,'bob');assert.equal(await alice.getByText('@bob',{exact:true}).count(),0);});
 await check('create team from empty workspace',async()=>{const f=form(alice,'New team');await f.getByLabel('Team name').fill('Acme engineering');await f.getByRole('button',{name:'Create team',exact:true}).click();await alice.getByText('Team created.',{exact:true}).waitFor();await alice.getByRole('heading',{name:'Add your first project'}).waitFor();});
 await check('project requires GitHub repository administration',async()=>{const f=form(alice,'Add project');await f.getByLabel('Project name').fill('Web app');await f.getByLabel('GitHub repository').fill('acme/no-admin');await f.getByRole('button',{name:'Create project',exact:true}).click();await alice.getByRole('alert').filter({hasText:'administrator access is required'}).waitFor();});
 await check('provision project and read live empty cache',async()=>{const f=form(alice,'Add project');await f.getByLabel('GitHub repository').fill('acme/web');await f.getByRole('button',{name:'Create project',exact:true}).click();await alice.getByText('Project created. Connect your CLI to start caching.').waitFor();await alice.getByText('No measured lookups',{exact:true}).waitFor();assert.equal(await alice.getByRole('heading',{name:'Web app',exact:true}).count(),1);});
 let project='';
 await check('CLI connection command contains selected cloud and project',async()=>{const command=await alice.locator('pre').innerText();assert.ok(command.includes(`--cloud '${origin}'`));assert.ok(command.includes('--github-cli'));project=command.match(/--project '([^']+)'/)![1]!;assert.ok(project);});
 await check('CLI connect exchanges GitHub credentials and uploads real cache bytes',async()=>{const cliRoot=fs.mkdtempSync('/tmp/layercache-cloud-cli-');fs.writeFileSync(path.join(cliRoot,'gh'),'#!/bin/sh\nprintf \'fixture-github-alice\\n\'\n',{mode:0o700});const configPath=path.join(cliRoot,'project.json');const connected=spawnSync(process.env.LAYERCACHE_BIN!,['connect','--cloud',origin,'--project',project,'--github-cli','--config',configPath,'--json'],{encoding:'utf8',timeout:20000,env:{...process.env,PATH:cliRoot+path.delimiter+process.env.PATH,XDG_CACHE_HOME:path.join(cliRoot,'cache'),XDG_CONFIG_HOME:path.join(cliRoot,'config')}});assert.equal(connected.status,0,connected.stderr);const config: {teamToken:string;compatibilityId:string;projectId:string;teamUrl:string}=JSON.parse(fs.readFileSync(configPath,'utf8'));assert.equal(config.projectId,project);assert.equal(config.teamUrl,origin);const token=config.teamToken;const put=await alice.request.put(origin+'/v8/artifacts/qa-ui-artifact',{headers:{Authorization:'Bearer '+token,'X-LayerCache-Compatibility':config.compatibilityId},data:'cache-data'.repeat(1024)});assert.equal(put.status(),200);await alice.getByRole('button',{name:'Refresh',exact:true}).click();await alice.getByText('10.0 KiB',{exact:true}).waitFor();});
 await check('invite reader and accept as intended account',async()=>{const f=form(alice,'Invite teammate');await f.getByLabel('GitHub username').fill('bob');await f.getByRole('combobox').selectOption('reader');await f.getByRole('button',{name:'Send invitation'}).click();await alice.getByText('Invitation ready.',{exact:false}).waitFor();await bob.getByRole('button',{name:'Refresh',exact:true}).click();await bob.getByRole('heading',{name:'Join Acme engineering'}).waitFor();await bob.getByRole('button',{name:'Accept invitation'}).click();await bob.getByText('Invitation accepted.',{exact:true}).waitFor();await bob.getByText('10.0 KiB',{exact:true}).waitFor();});
 await check('reader can see cache and cannot administer',async()=>{assert.equal(await bob.getByRole('button',{name:'Create project',exact:true}).count(),0);assert.equal(await bob.getByRole('button',{name:'Send invitation',exact:true}).count(),0);assert.equal(await bob.getByRole('button',{name:'Save role',exact:true}).count(),0);assert.match(await bob.locator('main').innerText(),/reader/);});
 await check('administrator promotes reader to writer',async()=>{await alice.getByRole('button',{name:'Refresh',exact:true}).click();await alice.getByLabel('Role for bob').selectOption('writer');const member=alice.locator('.member').filter({has:alice.getByText('@bob',{exact:true})});await member.getByRole('button',{name:'Save role'}).click();await alice.getByText('Role updated.',{exact:true}).waitFor();await bob.getByRole('button',{name:'Refresh',exact:true}).click();await bob.getByText('Acme engineering / writer',{exact:true}).waitFor();assert.equal(await bob.getByRole('button',{name:'Create project',exact:true}).count(),0);});
 await check('session survives reload and reporting period changes',async()=>{await bob.reload();await bob.getByText('10.0 KiB',{exact:true}).waitFor();const response=bob.waitForResponse(r=>r.url().includes('/snapshot?period=7d'));await bob.getByLabel('Reporting period').selectOption('7d');assert.equal((await response).status(),200);});
 for(const width of [320,390,768,1440])await check(`viewport ${width}`,async()=>{await alice.setViewportSize({width,height:900});assert.equal(await alice.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await alice.screenshot({path:path.join(output,`viewport-${width}.png`),fullPage:true});});
 await check('last administrator protection reaches UI',async()=>{await alice.getByLabel('Role for alice').selectOption('reader');const member=alice.locator('.member').filter({has:alice.getByText('@alice',{exact:true})});await member.getByRole('button',{name:'Save role'}).click();await alice.getByRole('alert').filter({hasText:'last administrator'}).waitFor();});
 await check('remove member immediately removes project visibility',async()=>{alice.once('dialog',dialog=>dialog.accept());await alice.locator('.member').filter({has:alice.getByText('@bob',{exact:true})}).getByRole('button',{name:'Remove'}).click();await alice.getByText('Member removed.',{exact:true}).waitFor();await bob.getByRole('button',{name:'Refresh',exact:true}).click();await bob.getByRole('heading',{name:'Welcome to your cloud workspace'}).waitFor();assert.equal(await bob.getByRole('heading',{name:'Web app',exact:true}).count(),0);});
 await check('sign out destroys browser session',async()=>{await bob.getByRole('button',{name:'Sign out',exact:true}).click();await bob.getByRole('link',{name:'Continue with GitHub'}).waitFor();await bob.reload();await bob.getByRole('link',{name:'Continue with GitHub'}).waitFor();});
 await check('expired server session clears private workspace',async()=>{await alice.route('**/api/session',route=>route.fulfill({status:401,json:{error:'expired'}}));await alice.getByRole('button',{name:'Refresh',exact:true}).click();await alice.getByRole('link',{name:'Continue with GitHub'}).waitFor();assert.equal(await alice.locator('pre').count(),0);assert.equal(await alice.getByRole('heading',{name:'Web app',exact:true}).count(),0);});
 await check('no browser exceptions',async()=>assert.deepEqual(errors,[]));
}catch(error){console.error(error);}finally{fs.writeFileSync(path.join(output,'results.json'),JSON.stringify(results,null,2));console.log(JSON.stringify({browser:engine,output,results},null,2));await browser.close();if(results.some(r=>!r.passed))process.exitCode=1;}
