type Team = {id:string;name:string;role:string};
type Project = {id:string;teamId:string;name:string;repository:string;role:string};
type Member = {userId:string;login:string;role:string};
type Session = {user:{id:string;login:string};csrfToken:string;cloudOrigin:string;teams:Team[]|null;projects:Project[]|null;invitations:{id:string;teamName:string;role:string}[]|null};
type Snapshot = {cache:{state:string;reportState:string;status?:{usageBytes:number;maxBytes:number|null;artifacts:number};report?:{hits:number;misses:number;runs:number;hitRate:number}};updatedAt:string};
const root = document.querySelector<HTMLElement>('#app')!;
const notice = document.querySelector<HTMLElement>('#notice')!;
let session:Session|undefined, selectedTeam='', selectedProject='', generation=0;
class Unauthorized extends Error {}
function el<K extends keyof HTMLElementTagNameMap>(tag:K,text='',className=''):HTMLElementTagNameMap[K] {const node=document.createElement(tag);node.textContent=text;if(className)node.className=className;return node;}
function message(text:string,error=false){notice.textContent=text;notice.className=error?'notice error':'notice';notice.setAttribute('role',error?'alert':'status');}
async function api<T>(path:string,method='GET',body?:unknown):Promise<T>{
 const response=await fetch(path,{method,credentials:'same-origin',headers:{'Content-Type':'application/json',...(method!=='GET'?{'X-CSRF-Token':session?.csrfToken??''}:{})},...(body===undefined?{}:{body:JSON.stringify(body)}),signal:AbortSignal.timeout(20000)});
 if(response.status===401){session=undefined;generation++;renderLogin();throw new Unauthorized('Your session expired. Sign in to continue.');}
 if(!response.ok){let detail='Request failed. Please try again.';try{detail=(await response.json()).error??detail;}catch{}throw new Error(detail);}
 return response.status===204?undefined as T:await response.json() as T;
}
function button(text:string,action:()=>Promise<void>|void,className=''):HTMLButtonElement {const b=el('button',text,className);b.type='button';b.onclick=async()=>{b.disabled=true;message('');try{await action();}catch(error){message(error instanceof Error?error.message:'Request failed',true);}finally{b.disabled=false;}};return b;}
function field(form:HTMLElement,label:string,name:string,placeholder='',required=true):HTMLInputElement{const wrap=el('label',label);const input=el('input');input.name=name;input.placeholder=placeholder;input.required=required;input.maxLength=name==='repository'?202:80;wrap.append(input);form.append(wrap);return input;}
function roleField(form:HTMLElement,label='Role',value='reader'){const wrap=el('label',label);const select=el('select');for(const role of ['reader','writer','admin']){const option=el('option',role);option.value=role;select.append(option);}select.value=value;wrap.append(select);form.append(wrap);return select;}
function form(title:string,submit:string,action:(form:HTMLFormElement)=>Promise<void>):HTMLFormElement {const node=el('form');node.append(el('h3',title));const b=el('button',submit);b.type='submit';node.onsubmit=async event=>{event.preventDefault();b.disabled=true;message('');try{await action(node);}catch(error){message(error instanceof Error?error.message:'Request failed',true);}finally{b.disabled=false;}};node.append(b);return node;}
function value(form:HTMLFormElement,name:string){return (form.elements.namedItem(name) as HTMLInputElement).value.trim();}
function appendField(form:HTMLFormElement,label:string,name:string,placeholder=''){const input=field(form,label,name,placeholder);form.append(form.querySelector('button')!);return input;}
function renderLogin(){root.replaceChildren();const card=el('section','','welcome');card.append(el('p','LAYER CACHE CLOUD','eyebrow'),el('h1','One cache. Your whole team.'),el('p','Connect your CLI, share project caches, and see what your builds reuse.'));const link=el('a','Continue with GitHub','primary');link.href='/auth/github';card.append(link,el('p','Create a team after signing in. Repository administrator access is required to add a project.','muted'));root.append(card);}
async function refresh(){session=await api<Session>('/api/session');const teams=session.teams??[];if(!teams.some(t=>t.id===selectedTeam))selectedTeam=teams[0]?.id??'';const projects=(session.projects??[]).filter(p=>p.teamId===selectedTeam);if(!projects.some(p=>p.id===selectedProject))selectedProject=projects[0]?.id??'';render();}
function render(){if(!session)return renderLogin();const current=session;const version=++generation;root.replaceChildren();const header=el('header');const brand=el('a','Layer Cache','brand');brand.href='/';header.append(brand,el('span',`@${current.user.login}`,'muted'),button('Refresh',refresh),button('Sign out',async()=>{await api('/api/logout','POST');session=undefined;generation++;renderLogin();message('Signed out.');}));root.append(header);
 const layout=el('div','','layout'),nav=el('nav'),main=el('main');nav.setAttribute('aria-label','Teams and projects');layout.append(nav,main);root.append(layout);nav.append(el('p','WORKSPACE','eyebrow'));
 const selector=el('select');selector.setAttribute('aria-label','Team');for(const team of current.teams??[]){const option=el('option',team.name);option.value=team.id;selector.append(option);}selector.value=selectedTeam;selector.onchange=()=>{selectedTeam=selector.value;selectedProject='';render();};if(current.teams?.length)nav.append(selector);
 const projects=(current.projects??[]).filter(p=>p.teamId===selectedTeam);if(!projects.some(p=>p.id===selectedProject))selectedProject=projects[0]?.id??'';
 nav.append(el('p','PROJECTS','eyebrow'));for(const project of projects){const b=button(project.name,()=>{selectedProject=project.id;render();},project.id===selectedProject?'selected':'');b.setAttribute('aria-pressed',String(project.id===selectedProject));nav.append(b);}
 if(!projects.length)nav.append(el('p','No projects yet.','muted'));
 const create=form('New team','Create team',async f=>{const team=await api<Team>('/api/teams','POST',{name:value(f,'name')});selectedTeam=team.id;selectedProject='';await refresh();message('Team created.');});appendField(create,'Team name','name','Acme engineering');nav.append(create);
 for(const invite of current.invitations??[]){const card=el('section','','card');card.append(el('h2',`Join ${invite.teamName}`),el('p',`You were invited as a ${invite.role}.`),button('Accept invitation',async()=>{await api(`/api/invitations/${encodeURIComponent(invite.id)}/accept`,'POST');await refresh();message('Invitation accepted.');}));main.append(card);}
 const team=(current.teams??[]).find(t=>t.id===selectedTeam);if(!team){main.append(el('h1','Welcome to your cloud workspace'),el('p','Create a team to share caches, or accept an invitation above.'));return;}
 main.append(el('p',`${team.name} / ${team.role}`,'eyebrow'));const project=projects.find(p=>p.id===selectedProject);
 if(project){main.append(el('h1',project.name),el('p',project.repository,'muted'));const cache=el('section','','card');cache.setAttribute('aria-label','Cache visibility');cache.append(el('h2','Cache activity'));const period=el('select');period.setAttribute('aria-label','Reporting period');for(const [id,text] of [['24h','Last 24 hours'],['7d','Last 7 days']]){const o=el('option',text!);o.value=id!;period.append(o);}const metrics=el('div');cache.append(period,metrics);main.append(cache);let request=0;
 const load=async()=>{const order=++request;metrics.replaceChildren(el('p','Loading cache activity…'));try{const snapshot=await api<Snapshot>(`/api/projects/${encodeURIComponent(project.id)}/snapshot?period=${period.value}`);if(version!==generation||order!==request)return;metrics.replaceChildren();const status=snapshot.cache.status;if(snapshot.cache.state!=='connected'||!status){metrics.append(el('p','Cache unavailable. Refresh to retry.','error'));return;}const stats=el('div','','metrics');const metric=(label:string,text:string)=>{const box=el('div');box.append(el('span',label,'muted'),el('strong',text));stats.append(box);};metric('Stored',bytes(status.usageBytes));metric('Storage limit',status.maxBytes===null?'Not configured':bytes(status.maxBytes));metric('Artifacts',String(status.artifacts));const report=snapshot.cache.report;if(snapshot.cache.reportState==='connected'&&report){metric('Cache hits',String(report.hits));metric('Cache misses',String(report.misses));metric('Hit rate',report.hits+report.misses?`${(report.hitRate*100).toFixed(1)}%`:'No measured lookups');}metrics.append(stats);if(snapshot.cache.reportState!=='connected')metrics.append(el('p','Activity report unavailable. Storage is current.','error'));metrics.append(el('p',`Updated ${new Date(snapshot.updatedAt).toLocaleString()}`,'muted'));}catch(error){if(version===generation&&order===request)metrics.replaceChildren(el('p',error instanceof Error?error.message:'Cache unavailable','error'));}};
 period.onchange=()=>{void load();};void load();const connect=el('section','','card');connect.append(el('h2','Connect your CLI'),el('p','Run this inside your repository with the LayerCache CLI installed.'));const command=`layercache connect --cloud '${current.cloudOrigin.replaceAll("'","'\\''")}' --project '${project.id}' --github-cli`;connect.append(el('pre',command),el('p','Uses your GitHub CLI sign-in. Omit --github-cli to sign in through a browser code.','muted'));connect.append(button('Copy command',async()=>{await navigator.clipboard.writeText(command);message('Connection command copied.');}));main.append(connect);
 }else{main.append(el('h1','Add your first project'),el('p','Projects keep cache artifacts isolated. Team members share access according to their role.'));}
 if(team.role==='admin'){const add=form('Add project','Create project',async f=>{const project=await api<Project>(`/api/teams/${team.id}/projects`,'POST',{name:value(f,'name'),repository:value(f,'repository')});selectedProject=project.id;await refresh();message('Project created. Connect your CLI to start caching.');});appendField(add,'Project name','name','Web app');appendField(add,'GitHub repository','repository','owner/repository');add.append(el('p','Your GitHub account must administer this repository.','muted'));main.append(add);}
 const members=el('section','','card');members.append(el('h2','Team access'),el('p','Readers restore caches. Writers also upload. Administrators manage the team and its projects.','muted'));main.append(members);void api<Member[]>(`/api/teams/${team.id}/members`).then(list=>{if(version!==generation)return;for(const member of list??[]){const row=el('div','','member');row.append(el('strong',`@${member.login}`));if(team.role==='admin'){const role=roleField(row,`Role for ${member.login}`,member.role);row.append(button('Save role',async()=>{await api(`/api/teams/${team.id}/members/${member.userId}`,'PUT',{role:role.value});await refresh();message('Role updated.');}),button('Remove',async()=>{if(!window.confirm(`Remove @${member.login} from ${team.name}? Their cache access will end.`))return;await api(`/api/teams/${team.id}/members/${member.userId}`,'DELETE');await refresh();message('Member removed.');},'danger'));}else row.append(el('span',member.role));members.append(row);}}).catch(error=>{if(version===generation)members.append(el('p',error instanceof Error?error.message:'Unable to load members','error'));});
 if(team.role==='admin'){let role:HTMLSelectElement;const invite=form('Invite teammate','Send invitation',async f=>{await api(`/api/teams/${team.id}/invitations`,'POST',{login:value(f,'login'),role:role.value});f.reset();message('Invitation ready. Ask your teammate to sign in here within 7 days and accept it.');});appendField(invite,'GitHub username','login','teammate');role=roleField(invite);invite.append(invite.querySelector('button')!);invite.append(el('p','Invitations appear when your teammate signs in. No email is sent.','muted'));members.append(invite);}
}
function bytes(value:number){if(value===0)return '0 B';const units=['B','KiB','MiB','GiB','TiB'];const i=Math.min(Math.floor(Math.log(value)/Math.log(1024)),4);return `${(value/1024**i).toFixed(i?1:0)} ${units[i]}`;}
void refresh().catch(error=>{if(error instanceof Unauthorized){message('');return;}root.replaceChildren(el('h1','Unable to load your workspace'),button('Retry',refresh));message(error instanceof Error?error.message:'Please retry',true);});
